version: "3"
networks:
  koala_network:

services:
  brain_miners:
    networks:
      - koala_network
    image: brain_miners:latest
    ports:
      - "8080:8080"
    depends_on:
      - psql_db
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://psql_db:5432/postgres
      JDBC_DATABASE_USER: gg
      JDBC_DATABASE_PASSWORD: Qwert123
  psql_db:
    networks:
      - koala_network
    container_name: psql_db
    expose:
      - 5432
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: gg
      POSTGRES_PASSWORD: Qwert123