server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://184732:eyJrIjoiMTUwYjJkODhmMjU2Mzg4ZTU5YzFlZWMxZTdmMWNmYjVhMTQzYjNkNyIsIm4iOiJicmFpbl9taW5lciIsImlkIjo2MjA1Mjd9@logs-prod-eu-west-0.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring-demo
          __path__: /var/log/monitoring.log
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level: